Fix missing property
Traceback (most recent call last):
  File
"/home/amorton/tablesnap/.env/lib/python2.6/site-packages/tablesnap/scri
pts.py", line 126, in tablesnap_main
    rv, out = sub_command()
  File
"/home/amorton/tablesnap/.env/lib/python2.6/site-packages/tablesnap/subc
ommands/restore_subcommand.py", line 177, in __call__
    if op_result.failed
AttributeError: 'RestoreResult' object has no attribute 'failed'